{
 "title": "NVIDIA Jetson",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "JOB", "query": "nvidia_jetson" }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_uptime" }
   ]
  },
  {
   "title": "Board Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "gpu_info_board_info" }
   ]
  },
  {
   "title": "Board Hardware Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "gpu_info_hardware_info" }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "gpu_usage_gpu" }
   ]
  },
  {
   "title": "Sensor Temperatures",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_temperatures" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_usage_cpu" }
   ]
  },
  {
   "title": "RAM Used",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_usage_ram" }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_usage_disk" }
   ]
  },
  {
   "title": "Power Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_usage_power" }
   ]
  }
 ]
}